### ISSUE TITLE
No icon displayed on the panel

### ISSUE THREAD

**Issue by gadicc** [mcrapet/mate-applet-switch#1]
Hey, this is awesome!

Every part of it works except actually showing an icon on the panel.  There's nothing there, but if I left / right click in the right place, it toggles / shows the context menu, respectively.

Any hints?  Where can I check for any debug info?

Thanks!

I'm using MATE Panel v1.12.2.

**Comment by mcrapet** [comment]
Hi,

You don't see at all the light switch ?
https://github.com/mcrapet/mate-applet-switch/blob/master/images/switch_on.png
https://github.com/mcrapet/mate-applet-switch/blob/master/images/switch_off.png

What is your distro and how did you installed mate-applet-switch, I'll try to reproduce your issue in a virtualbox.

**Comment by gadicc** [comment]
Hey, thanks for the quick reply!

Nope, nothing I'd all.  I'd send a screenshot but it would be literally just the color of my panel :>

Wow, that's over and above what I'd expect from any maintainer (including myself!), thanks a lot.  I'm on an up-to-date Archlinux (possibly same as you, judging from INSTALL?).  Installed from git clone via INSTALL instructions.

_Actually, I just restarted mate-panel and now it's working.  Go figure.  Maybe because I had initially installed to /usr/local, then switched to /usr, and maybe mate-panel is overly aggressive at caching._

Anyway, thanks again for willingness to check in a VM.

**Comment by gadicc** [comment]
Oh and thanks again for this beaut, so handy!
